### ISSUE TITLE
Using Laravel .env variables

### ISSUE THREAD

**Issue by SamuelMwangiW** [aschmelyun/docker-compose-laravel#111]
While working on a project I like to leverage Laravel's `.env` file to populate the `docker-compose.yml`. This allows for a single source of truth for variables such a database credentials and has the added benefit of 1. not accidentally committing credentials to version control and 2. Using different credentials per environment while using the same `YAML`.

I would therefore run docker-compose as `docker-compose --env-file src/.env up -d` and the mysql service of `docker-composer.yaml` would look like:

```YAML

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
```

@aschmelyun would you accept a PR for the same?
