### ISSUE TITLE
Laravel dusk

### ISSUE THREAD

**Issue by KevinBeckers** [aschmelyun/docker-compose-laravel#183]
Thank you for this awesome repo! I was wondering if you have any advice on Laravel Dusk regarding the Docker setup.

**Comment by KevinBeckers** [comment]
Got it working with the following edits:
docker-compose -> add the selenium image
```
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
    - 4444:4444
    - 7900:7900
```

DuskTestCase.php -> change the driver
```
protected function driver()
    {
        return RemoteWebDriver::create(
            'http://127.0.0.1:4444/wd/hub', DesiredCapabilities::chrome()
        );
    }
```
