### ISSUE TITLE
How to run queue worker?

### ISSUE THREAD

**Issue by KevinYobeth** [aschmelyun/docker-compose-laravel#194]
As the title says, how to run queue worker in laravel on production environment?

**Comment by thrashzone13** [comment]
You can add a service for it using the php image
```
queue:
  image: php
  restart: unless-stopped
  command: bash -c 'php artisan queue:work;'
  container_name: queue
  depends_on:
      - redis
  volumes:
    - ./src:/var/www/html:delegated
  networks:
    - laravel
```
