### ISSUE TITLE
extension=mongodb.so

### ISSUE THREAD

**Issue by mdabbagh-ir** [aschmelyun/docker-compose-laravel#198]
Hi

in php.dockerfile
`RUN echo "extension=mongodb.so" >> /usr/local/etc/php/php.ini
`

in docker-compose.yml
```
 mongo:
    image: mongo:4.4.6
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=musics
    networks:
      - laravel

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports: 
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - laravel
```
error is: Error: Class "MongoDB\Driver\Manager" not found in file /var/www/html/vendor/mongodb/mongodb/src/Client.php on line 124
