### ISSUE TITLE
Add support for Storybook

### ISSUE THREAD

**Issue by bhaidar** [aschmelyun/docker-compose-laravel#24]
Hi,
I've added the below to the docker compose file in case you are using Storybook with Laravel/Vue.

```
  storybook:
    image: node:13.7
    container_name: storybook
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: npm run storybook
    ports:
      - "8082:3002"
    networks:
      - laravel
```

Regards
Bilal
