### ISSUE TITLE
Tried to add ssh container but of course couldn't reach to php

### ISSUE THREAD

**Issue by ahmadabuaysheh** [aschmelyun/docker-compose-laravel#31]
I tried to add an ssh container to the whole file to be able to connect to it using ssh command itself(I need this for a tool I'm using). 
So, I added this service but couldn't map the php command here to run inside it. 
I'll keep trying though to do this and update if I have something working.
```
  connector:
    image: abobija/ssh
    container_name: connector
    depends_on:
      - php
    ports:
      - "2222:22"
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    tty: true
    networks:
      - laravel
```
