### ISSUE TITLE
Question regarding networks: laravel and default

### ISSUE THREAD

**Issue by MrMagooThis** [aschmelyun/docker-compose-laravel#68]
Newbie here.

**AFTER** executing: ``andrew-beta(master) $ docker-compose up --build --detach site``

I noticed that there were 2 networks associated with this project...``laravel`` and ``default``.  **I am not sure if this was done for a reason?**

```
andrew-beta(master) $ docker network ls
NETWORK ID          NAME                  DRIVER              SCOPE
d0e11de5ac50        andrew-beta_default   bridge              local
639301a86522        andrew-beta_laravel   bridge              local
28eda924b827        bridge                bridge              local
3e067bc7e3c5        host                  host                local
6b8364dbf466        none                  null                local
```

If I add the ``laravel`` network to the ``npm`` service, as the other 5 services have, then the result is that these 6 services are all on the ``laravel`` network.  **Any reason to not to do this?**

```
  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
```

Thanks

Mike
