### ISSUE TITLE
Persisting MySQL: Permission Error

### ISSUE THREAD

**Issue by themangomago** [aschmelyun/docker-compose-laravel#70]
Ubuntu 18.04

```
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

```

PermissionError: [Errno 13] Permission denied: '/home/laravel/playground/docker/mysql/ca-key.pem'

Steps to reproduce:
- Add volume to mysql
- Set all up
- docker-compose down
- docker-compose up -d
