### ISSUE TITLE
Add SSL: HTTPS (Let's Encrypt) to NGINX and Certbot

### ISSUE THREAD

**Issue by handhikadj** [aschmelyun/docker-compose-laravel#78]
Please do this so that I can use this in production

**Comment by sidigi** [comment]
docker compose not for production

**Comment by handhikadj** [comment]
Do you have reason on that?

**Comment by slzrdev** [comment]
I've added a reverse proxy to the docker-compose.yml given by Andrew and it works. I haven't tested with letsencrypt but you can try something like this and after the steps in the Readme file do docker-compose down. Then restart everything with 
`docker-compose up -d --build`
and it SHOULD work. I'm not giving any warranty on this:


```
version: '3'

networks:
  laravel:

services:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - certs:/etc/nginx/certs:ro
    - vhostd:/etc/nginx/vhost.d
    - html:/usr/share/nginx/html
  labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  networks:
    - laravel

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - laravel

  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    expose:
      - "80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    environment:
      - VIRTUAL_HOST=your_domain.com,www.your_domain.com

```

Take a look at the environment setting "VIRTUAL_HOST" and fill with your domain and alias separated by a comma.

It's mandatory for Certbot to work that the domain is registered and properly delegated with A and AAAA DNS registries created.

Let me know if this works.
