### ISSUE TITLE
Cannot start service artisan no such file or directory

### ISSUE THREAD

**Issue by Bmooij** [aschmelyun/docker-compose-laravel#8]
```
ERROR: for artisan  Cannot start service artisan: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/var/www/html/artisan\": stat /var/www/html/artisan: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

I'm running windows 10. I've verified that the artisan file is present in the `src` directory.

**Comment by oranges13** [comment]
For anyone else having this issue, I had to modify the docker-compose.yml file for artisan as follows:

```yml
artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    entrypoint: ['php', '/var/www/html/artisan'] # Added 'php' before '/var/www/html/artisan'
    networks:
      - laravel
```
