### ISSUE TITLE
Hot reloading is lost.Cannot manage to set browserSync.

### ISSUE THREAD

**Issue by devellopah** [aschmelyun/docker-compose-laravel#89]
I have added browserSync to mix config and this is my config now
```javascript
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        //
    ])
    .browserSync({
        proxy: 'localhost:80', // is this correct?
        open: false,
        port: 3000,
    })
```
Adding this is not enough, there are other changes to be made in starter(docker-compose.yml, i assume).
So, please, update files to allow browserSync.

**Comment by aschmelyun** [comment]
Hi @devellopah, sorry for the delay in taking a look at this. I've come up with a solution that I'll lay out here. 

First, in your docker-compose.yml file, add the following ports to the npm service. The block for it should now look something like this:

```yaml
  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
```

Then, adjust your proxy in the code block you wrote above from `localhost:80` to `nginx`. 

After that's done, on your command line terminal at the project root, run the following command to start BrowserSync:

```bash
docker-compose run --rm --service-ports npm run watch
```

After running, an info panel should remain in your command line and prompt you to open your browser to `http://localhost:3000` where you should see your hot-reloading.

I've committed the ports changes to the docker-compose.yml file in this main repo, but since this doesn't contain any Laravel project data, the rest will have to be done manually by those who want to enable BrowserSync. I've updated the README to contain information on how to do it, and will keep this issue open for now in case anyone has questions or concerns!
