### ISSUE TITLE
add mailhog in docker-compose (suggestion)

### ISSUE THREAD

**Issue by scwall** [aschmelyun/docker-compose-laravel#97]
add mailhog in docker-compose for test email 👍 
```
 mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - laravel
```

**Comment by Albertopeinado96** [comment]
This is already in the docker-compose.yml file

```
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel
```
